"""improve cloud account model

Revision ID: 0786f301a32e
Revises: 
Create Date: 2026-08-06 16:11:44.794540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0786f301a32e'
down_revision: Union[str, Sequence[str], None] = "000000000001"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cloud_accounts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
    op.drop_constraint(op.f('cloud_accounts_account_id_key'), 'cloud_accounts', type_='unique')
    op.create_index(op.f('ix_cloud_accounts_account_id'), 'cloud_accounts', ['account_id'], unique=True)
    op.create_index(op.f('ix_cloud_accounts_provider'), 'cloud_accounts', ['provider'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cloud_accounts_provider'), table_name='cloud_accounts')
    op.drop_index(op.f('ix_cloud_accounts_account_id'), table_name='cloud_accounts')
    op.create_unique_constraint(op.f('cloud_accounts_account_id_key'), 'cloud_accounts', ['account_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('cloud_accounts', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###
