"""add incidents table

Revision ID: 9cf39fb4fab8
Revises: e34251cbf291
Create Date: 2026-08-12 20:22:43.392121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cf39fb4fab8'
down_revision: Union[str, Sequence[str], None] = 'e34251cbf291'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incidents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('cloud_provider', sa.String(length=20), nullable=False),
    sa.Column('account_id', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('source_ip', sa.String(length=64), nullable=True),
    sa.Column('user_identity', sa.String(length=255), nullable=True),
    sa.Column('correlation_rule_id', sa.String(length=100), nullable=True),
    sa.Column('alert_ids', sa.JSON(), nullable=False),
    sa.Column('event_ids', sa.JSON(), nullable=False),
    sa.Column('mitre_tactic', sa.String(length=100), nullable=True),
    sa.Column('mitre_technique', sa.String(length=255), nullable=True),
    sa.Column('mitre_technique_id', sa.String(length=50), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incidents_account_id'), 'incidents', ['account_id'], unique=False)
    op.create_index(op.f('ix_incidents_cloud_provider'), 'incidents', ['cloud_provider'], unique=False)
    op.create_index(op.f('ix_incidents_correlation_rule_id'), 'incidents', ['correlation_rule_id'], unique=False)
    op.create_index(op.f('ix_incidents_created_at'), 'incidents', ['created_at'], unique=False)
    op.create_index(op.f('ix_incidents_id'), 'incidents', ['id'], unique=False)
    op.create_index(op.f('ix_incidents_incident_id'), 'incidents', ['incident_id'], unique=True)
    op.create_index(op.f('ix_incidents_severity'), 'incidents', ['severity'], unique=False)
    op.create_index(op.f('ix_incidents_source_ip'), 'incidents', ['source_ip'], unique=False)
    op.create_index(op.f('ix_incidents_status'), 'incidents', ['status'], unique=False)
    op.create_index(op.f('ix_incidents_user_identity'), 'incidents', ['user_identity'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_incidents_user_identity'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_status'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_source_ip'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_severity'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_incident_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_created_at'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_correlation_rule_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_cloud_provider'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_account_id'), table_name='incidents')
    op.drop_table('incidents')
    # ### end Alembic commands ###
