"""add asset risk refresh timestamp

Revision ID: c5b3a6a4d822
Revises: c5da9401ba26
Create Date: 2026-08-19 14:08:33.147175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5b3a6a4d822'
down_revision: Union[str, Sequence[str], None] = 'c5da9401ba26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('risk_updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'risk_updated_at')
    # ### end Alembic commands ###
