"""add resource context to alerts

Revision ID: c5da9401ba26
Revises: 905289aa3f4a
Create Date: 2026-08-18 11:20:33.928669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5da9401ba26'
down_revision: Union[str, Sequence[str], None] = '905289aa3f4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('resource_type', sa.String(length=100), nullable=True))
    op.add_column('alerts', sa.Column('resource_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_alerts_resource_id'), 'alerts', ['resource_id'], unique=False)
    op.create_index(op.f('ix_alerts_resource_type'), 'alerts', ['resource_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alerts_resource_type'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_resource_id'), table_name='alerts')
    op.drop_column('alerts', 'resource_id')
    op.drop_column('alerts', 'resource_type')
    # ### end Alembic commands ###
