"""upgrade alert model for phase 4

Revision ID: f88240a34606
Revises: 0786f301a32e
Create Date: 2026-08-12 19:12:38.809536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f88240a34606'
down_revision: Union[str, Sequence[str], None] = '0786f301a32e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('alert_id', sa.String(length=36), nullable=False))
    op.add_column('alerts', sa.Column('rule_id', sa.String(length=100), nullable=False))
    op.add_column('alerts', sa.Column('rule_name', sa.String(length=255), nullable=False))
    op.add_column('alerts', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('alerts', sa.Column('event_id', sa.String(length=255), nullable=False))
    op.add_column('alerts', sa.Column('event_name', sa.String(length=255), nullable=False))
    op.add_column('alerts', sa.Column('detection_key', sa.String(length=255), nullable=True))
    op.add_column('alerts', sa.Column('cloud_provider', sa.String(length=20), nullable=False))
    op.add_column('alerts', sa.Column('account_id', sa.String(length=100), nullable=True))
    op.add_column('alerts', sa.Column('region', sa.String(length=100), nullable=True))
    op.add_column('alerts', sa.Column('service', sa.String(length=100), nullable=True))
    op.add_column('alerts', sa.Column('source_ip', sa.String(length=64), nullable=True))
    op.add_column('alerts', sa.Column('user_identity', sa.String(length=255), nullable=True))
    op.add_column('alerts', sa.Column('incident_id', sa.String(length=100), nullable=True))
    op.add_column('alerts', sa.Column('mitre_tactic', sa.String(length=100), nullable=True))
    op.add_column('alerts', sa.Column('mitre_technique', sa.String(length=255), nullable=True))
    op.add_column('alerts', sa.Column('mitre_technique_id', sa.String(length=50), nullable=True))
    op.add_column('alerts', sa.Column('metadata', sa.JSON(), nullable=False))
    op.add_column('alerts', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('alerts', sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('alerts', sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('alerts', 'severity',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('alerts', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('alerts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
    op.create_index(op.f('ix_alerts_account_id'), 'alerts', ['account_id'], unique=False)
    op.create_index(op.f('ix_alerts_alert_id'), 'alerts', ['alert_id'], unique=True)
    op.create_index(op.f('ix_alerts_cloud_provider'), 'alerts', ['cloud_provider'], unique=False)
    op.create_index(op.f('ix_alerts_created_at'), 'alerts', ['created_at'], unique=False)
    op.create_index(op.f('ix_alerts_detection_key'), 'alerts', ['detection_key'], unique=True)
    op.create_index(op.f('ix_alerts_event_id'), 'alerts', ['event_id'], unique=False)
    op.create_index(op.f('ix_alerts_id'), 'alerts', ['id'], unique=False)
    op.create_index(op.f('ix_alerts_incident_id'), 'alerts', ['incident_id'], unique=False)
    op.create_index(op.f('ix_alerts_rule_id'), 'alerts', ['rule_id'], unique=False)
    op.create_index(op.f('ix_alerts_severity'), 'alerts', ['severity'], unique=False)
    op.create_index(op.f('ix_alerts_source_ip'), 'alerts', ['source_ip'], unique=False)
    op.create_index(op.f('ix_alerts_status'), 'alerts', ['status'], unique=False)
    op.create_index(op.f('ix_alerts_user_identity'), 'alerts', ['user_identity'], unique=False)
    op.drop_column('alerts', 'message')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('message', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_alerts_user_identity'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_status'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_source_ip'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_severity'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_rule_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_incident_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_event_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_detection_key'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_created_at'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_cloud_provider'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_alert_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_account_id'), table_name='alerts')
    op.alter_column('alerts', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('alerts', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('alerts', 'severity',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('alerts', 'resolved_at')
    op.drop_column('alerts', 'acknowledged_at')
    op.drop_column('alerts', 'updated_at')
    op.drop_column('alerts', 'metadata')
    op.drop_column('alerts', 'mitre_technique_id')
    op.drop_column('alerts', 'mitre_technique')
    op.drop_column('alerts', 'mitre_tactic')
    op.drop_column('alerts', 'incident_id')
    op.drop_column('alerts', 'user_identity')
    op.drop_column('alerts', 'source_ip')
    op.drop_column('alerts', 'service')
    op.drop_column('alerts', 'region')
    op.drop_column('alerts', 'account_id')
    op.drop_column('alerts', 'cloud_provider')
    op.drop_column('alerts', 'detection_key')
    op.drop_column('alerts', 'event_name')
    op.drop_column('alerts', 'event_id')
    op.drop_column('alerts', 'description')
    op.drop_column('alerts', 'rule_name')
    op.drop_column('alerts', 'rule_id')
    op.drop_column('alerts', 'alert_id')
    # ### end Alembic commands ###
